/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PinnedTextDialog.java
 *
 * Created on Aug 31, 2009, 4:17:03 PM
 */

package ui.dialog;

import ui.component.SetHotKeyButton;
import java.awt.Color;
import java.awt.Dialog;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextPane;
import model.PinnedText;
import model.Style;

/**
 *
 * @author anthony
 */
class PinnedTextDialog extends AbstractDetailDialog {

  protected PinnedText pinnedText;
  protected Vector<Style> styles;

  public static PinnedText showAddPinnedTextDialog(Dialog parent, Color backgroundColor, Vector<Style> styles) {
    PinnedTextDialog dialog = new PinnedTextDialog(parent, "Add New Pinned Text", null, backgroundColor, styles);
    dialog.setVisible(true);
    return (PinnedText) dialog._getFinalObject();
  }

  public static void showEditPinnedTextDialog(Dialog parent, PinnedText pinnedText, Color backgroundColor, Vector<Style> styles) {
    PinnedTextDialog dialog = new PinnedTextDialog(parent, "Edit Pinned Text", pinnedText, backgroundColor, styles);
    dialog.setVisible(true);
  }

  private PinnedTextDialog(Dialog parent, String title, PinnedText pinnedText,
          Color backgroundColor, Vector<Style> styles) {
    super(parent, title, backgroundColor);

    // TODO this is ugly, figure out a  better way
    if (pinnedText == null) {
      this.pinnedText = new PinnedText();
      this.pinnedText.setStyle(styles.firstElement());
      this.pinnedText.setRemovable(true);
      _setObject(this.pinnedText);
    } else {
      this.pinnedText = pinnedText;
    }
    _setObject(this.pinnedText);

    this.styles = styles;
    _setupComponents();
  }

  private void _setupComponents() {
    stylesList.setRenderer(new ListRenderer());
    stylesList.setModel(new DefaultComboBoxModel(styles));
    _registerCommitButton(okButton);
    _registerCancelButton(cancelButton);

    // initialize with data
    // TODO: Check threading here!  UI might get set which triggers events
    // that might not get dispatched until after listeners get added!
    _updateUIFromModel();
    _processUIChange();

    // setup change listener for UI components
    nameField.addCaretListener(this);
    textField.addCaretListener(this);
    stylesList.addActionListener(this);
    setKeyButton.addChangeListener(this);
  }

  // Methods that implement AbstractDetailDialog
  protected void _createComponents() {
    initComponents();
  }

  protected JTextPane _getPreviewPane() {
    return previewPane;
  }

  protected void _onValid() {
    okButton.setEnabled(true);
  }

  protected void _onInvalid() {
    okButton.setEnabled(false);
  }

  protected void _updateUIFromModel() {
    // TODO be careful with null values!
    nameField.setText(pinnedText.getName());
    textField.setText(pinnedText.getText());
    if (pinnedText.getHotKey() != null) {
      hotKeyField.setText(pinnedText.getHotKey().toString());
      ((SetHotKeyButton) setKeyButton).setCapturedKeyStroke(pinnedText.getHotKey());
    }
    stylesList.setSelectedItem(pinnedText.getStyle());
  }

  protected void _updateModelFromUI() {
    pinnedText.setName(nameField.getText());
    pinnedText.setText(textField.getText());
    pinnedText.setHotKey(((SetHotKeyButton) setKeyButton).getCapturedKeyStroke());
    pinnedText.setStyle((Style) stylesList.getSelectedItem());
  }
  //

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel5 = new javax.swing.JLabel();
    cancelButton = new javax.swing.JButton();
    okButton = new javax.swing.JButton();
    jScrollPane5 = new javax.swing.JScrollPane();
    previewPane = new javax.swing.JTextPane();
    stylesList = new javax.swing.JComboBox();
    hotKeyField = new javax.swing.JTextField();
    setKeyButton = new SetHotKeyButton(this, hotKeyField);
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    textField = new javax.swing.JTextArea();
    nameField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel5.setText("Style:");

    cancelButton.setText("Cancel");

    okButton.setText("OK");

    previewPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
    jScrollPane5.setViewportView(previewPane);

    stylesList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    hotKeyField.setText("None");
    hotKeyField.setEnabled(false);

    setKeyButton.setText("Set Key");

    jLabel3.setText("Text:");

    jLabel4.setText("HotKey:");

    textField.setColumns(15);
    textField.setRows(5);
    jScrollPane2.setViewportView(textField);

    jLabel1.setText("Name:");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel3)
              .add(jLabel1)
              .add(jLabel4)
              .add(jLabel5))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(stylesList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createSequentialGroup()
                  .add(hotKeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(setKeyButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jScrollPane2))))
          .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(okButton)
            .add(18, 18, 18)
            .add(cancelButton)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jLabel3)
          .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(30, 30, 30)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(hotKeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(setKeyButton))
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(stylesList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(18, 18, 18)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(cancelButton)
          .add(okButton))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextField hotKeyField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextField nameField;
  private javax.swing.JButton okButton;
  private javax.swing.JTextPane previewPane;
  private javax.swing.JButton setKeyButton;
  private javax.swing.JComboBox stylesList;
  private javax.swing.JTextArea textField;
  // End of variables declaration//GEN-END:variables

}
