/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoleDialog.java
 *
 * Created on Aug 12, 2009, 11:30:54 AM
 */
package ui.dialog;

import ui.component.SetHotKeyButton;
import java.awt.Color;
import java.awt.Dialog;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextPane;
import model.Role;
import model.Style;

/**
 *
 * @author anthony
 */
class RoleDialog extends AbstractDetailDialog {

  protected Role role;
  protected Vector<Style> styles;

  public static Role showAddRoleDialog(Dialog parent, Color backgroundColor, Vector<Style> styles) {
    RoleDialog dialog = new RoleDialog(parent, "Add New Role", null, backgroundColor, styles);
    dialog.setVisible(true);
    return (Role) dialog._getFinalObject();
  }

  public static void showEditRoleDialog(Dialog parent, Role role, Color backgroundColor, Vector<Style> styles) {
    RoleDialog dialog = new RoleDialog(parent, "Edit Role", role, backgroundColor, styles);
    dialog.setVisible(true);
  }

  /** Creates new form RoleDialog */
  private RoleDialog(Dialog parent, String title, Role role,
          Color backgroundColor, Vector<Style> styles) {
    super(parent, title, backgroundColor);

    // TODO this is ugly, figure out a  better way
    if (role == null) {
      this.role = new Role();
      this.role.setRemovable(true);
      this.role.setStyle(styles.firstElement());
      _setObject(this.role);
    } else {
      this.role = role;
    }
    _setObject(this.role);

    this.styles = styles;
    _setupComponents();
  }

  private void _setupComponents() {
    stylesList.setRenderer(new ListRenderer());
    stylesList.setModel(new DefaultComboBoxModel(styles));
    _registerCommitButton(okButton);
    _registerCancelButton(cancelButton);

    // initialize with data
    // TODO: Check threading here!  UI might get set which triggers events
    // that might not get dispatched until after listeners get added!
    _updateUIFromModel();
    _processUIChange();

    // setup change listener for UI components
    nameField.addCaretListener(this);
    displayNameField.addCaretListener(this);
    showNameField.addActionListener(this);
    showNamePromptField.addActionListener(this);
    stylesList.addActionListener(this);
    setKeyButton.addChangeListener(this);
    parenthesizedField.addActionListener(this);
  }

  // Methods that implement AbstractDetailDialog
  protected void _createComponents() {
    initComponents();
  }

  protected JTextPane _getPreviewPane() {
    return previewPane;
  }

  protected void _onValid() {
    okButton.setEnabled(true);
  }

  protected void _onInvalid() {
    okButton.setEnabled(false);
  }

  protected void _updateUIFromModel() {
    // TODO be careful with null values!
    nameField.setText(role.getName());
    displayNameField.setText(role.getDisplayName());
    descriptionField.setText(role.getDescription());
    showNameField.setSelected(role.isNameDisplayed());
    showNamePromptField.setSelected(role.isPromptDisplayed());
    if (role.getHotKey() != null) {
      hotKeyField.setText(role.getHotKey().toString());
      ((SetHotKeyButton) setKeyButton).setCapturedKeyStroke(role.getHotKey());
    }
    stylesList.setSelectedItem(role.getStyle());
    parenthesizedField.setSelected(role.isParenthesized());
  }

  protected void _updateModelFromUI() {
    role.setName(nameField.getText());
    role.setDisplayName(displayNameField.getText());
    role.setDescription(descriptionField.getText());
    role.setNameDisplayed(showNameField.isSelected());
    role.setPromptDisplayed(showNamePromptField.isSelected());
    role.setHotKey(((SetHotKeyButton) setKeyButton).getCapturedKeyStroke());
    role.setStyle((Style) stylesList.getSelectedItem());
    role.setParenthesized(parenthesizedField.isSelected());
  }
  //

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nameField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    displayNameField = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    descriptionField = new javax.swing.JTextArea();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    hotKeyField = new javax.swing.JTextField();
    setKeyButton = new SetHotKeyButton(this, hotKeyField);
    showNameField = new javax.swing.JCheckBox();
    jScrollPane5 = new javax.swing.JScrollPane();
    previewPane = new javax.swing.JTextPane();
    jLabel8 = new javax.swing.JLabel();
    stylesList = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    showNamePromptField = new javax.swing.JCheckBox();
    parenthesizedField = new javax.swing.JCheckBox();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setText("Name:");

    okButton.setText("OK");

    cancelButton.setText("Cancel");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jLabel2.setText("Display Name:");

    descriptionField.setColumns(15);
    descriptionField.setRows(5);
    jScrollPane2.setViewportView(descriptionField);

    jLabel3.setText("Description:");

    jLabel4.setText("HotKey:");

    hotKeyField.setText("None");
    hotKeyField.setEnabled(false);

    setKeyButton.setText("Set Key");

    showNameField.setSelected(true);
    showNameField.setText("Insert name when triggered in dialogue");

    previewPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
    jScrollPane5.setViewportView(previewPane);

    jLabel8.setText("(if different from name)");

    stylesList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel5.setText("Style:");

    showNamePromptField.setSelected(true);
    showNamePromptField.setText("Insert name prompt at start of dialogue");

    parenthesizedField.setText("Wrap new dialogue in parentheses");

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(jLabel2)
                  .add(jLabel1)
                  .add(jLabel3)
                  .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                  .add(layout.createSequentialGroup()
                    .add(hotKeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(setKeyButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                  .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(layout.createSequentialGroup()
                    .add(12, 12, 12)
                    .add(jLabel8))
                  .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, nameField)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, displayNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
              .add(showNameField)
              .add(layout.createSequentialGroup()
                .add(170, 170, 170)
                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
          .add(layout.createSequentialGroup()
            .add(showNamePromptField)
            .addContainerGap(78, Short.MAX_VALUE))
          .add(layout.createSequentialGroup()
            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 303, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(52, Short.MAX_VALUE))
          .add(layout.createSequentialGroup()
            .add(jLabel5)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
            .add(stylesList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(52, 52, 52))
          .add(layout.createSequentialGroup()
            .add(parenthesizedField)
            .addContainerGap(111, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel2)
          .add(displayNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jLabel8)
        .add(29, 29, 29)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(jLabel3)
          .add(layout.createSequentialGroup()
            .add(18, 18, 18)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(6, 6, 6)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(hotKeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(setKeyButton))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(showNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(showNamePromptField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(parenthesizedField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(stylesList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(18, 18, 18)
        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(31, 31, 31)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(cancelButton)
          .add(okButton))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JTextArea descriptionField;
  private javax.swing.JTextField displayNameField;
  private javax.swing.JTextField hotKeyField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField nameField;
  private javax.swing.JButton okButton;
  private javax.swing.JCheckBox parenthesizedField;
  private javax.swing.JTextPane previewPane;
  private javax.swing.JButton setKeyButton;
  private javax.swing.JCheckBox showNameField;
  private javax.swing.JCheckBox showNamePromptField;
  private javax.swing.JComboBox stylesList;
  // End of variables declaration//GEN-END:variables
}
